<a href="https://colab.research.google.com/github/Zuhair0000/Pytorch-Bootcamp/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


Creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 7],
                       [9, 10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

Random Tensors

In [ ]:
random_torch = torch.rand(3, 4)
random_torch

tensor([[0.3677, 0.3775, 0.5438, 0.0099],
        [0.1856, 0.2120, 0.7245, 0.0132],
        [0.5729, 0.4768, 0.7785, 0.6011]])

In [ ]:
random_torch.ndim

2

Create random tensor with similar shape to an image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

Create tensor of all zeros

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor of all ones

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating tensor-like

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [6]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [7]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [8]:
float_16_tensor.dtype

torch.float16

In [9]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [10]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [11]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting Information from tensors

In [12]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6661, 0.6994, 0.9969, 0.3247],
        [0.6601, 0.8527, 0.7153, 0.8670],
        [0.1964, 0.1852, 0.8978, 0.2086]])

In [14]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.6661, 0.6994, 0.9969, 0.3247],
        [0.6601, 0.8527, 0.7153, 0.8670],
        [0.1964, 0.1852, 0.8978, 0.2086]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating tensors

In [16]:
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [17]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication

In [19]:
torch.matmul(tensor, tensor)

tensor(14)

In [21]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A, tensor_B

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [22]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [23]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [25]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor Aggregation

In [26]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [28]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [29]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [32]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding the positional min and max

In [33]:
x.argmin()

tensor(0)

In [34]:
x.argmax()

tensor(9)