<a href="https://colab.research.google.com/github/Zuhair0000/Pytorch-Bootcamp/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


Creating tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 7],
                       [9, 10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

Random Tensors

In [13]:
random_torch = torch.rand(3, 4)
random_torch

tensor([[0.5726, 0.4550, 0.2815, 0.7663],
        [0.1142, 0.3325, 0.7341, 0.2297],
        [0.1118, 0.9102, 0.2264, 0.6533]])

In [14]:
random_torch.ndim

2

Create random tensor with similar shape to an image tensor

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

Create tensor of all zeros

In [16]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor of all ones

In [17]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [18]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating tensor-like

In [19]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [22]:
float_16_tensor.dtype

torch.float16

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [24]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [25]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting Information from tensors

In [26]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7742, 0.6475, 0.3353, 0.5800],
        [0.9059, 0.2397, 0.9975, 0.8602],
        [0.9378, 0.3180, 0.8093, 0.6290]])

In [27]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7742, 0.6475, 0.3353, 0.5800],
        [0.9059, 0.2397, 0.9975, 0.8602],
        [0.9378, 0.3180, 0.8093, 0.6290]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manipulating tensors

In [28]:
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [29]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication

In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A, tensor_B

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [32]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [34]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Tensor Aggregation

In [35]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [39]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding the positional min and max

In [40]:
x.argmin()

tensor(0)

In [41]:
x.argmax()

tensor(9)

# Reshaping, stacking, squeezing and unsqueezing tensors

## Reshape

In [42]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

## Change view
Changin z changes x because a view of a tensor shares the same memory as the original input

In [47]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

## Stack tensors on top of each other

In [51]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

## Squeezing

In [53]:
x_reshaped.shape

torch.Size([1, 9])

In [58]:
x_squeezed = x_reshaped.squeeze()

In [59]:
x_reshaped.squeeze().shape

torch.Size([9])

## Unsqueezeing

In [63]:
x_squeezed.unsqueeze(dim=1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [66]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed.shape

torch.Size([1, 9])

## Permute

In [68]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)

In [69]:
x_original.shape

torch.Size([224, 224, 3])

In [71]:
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing

In [73]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
x[0][0]

tensor([1, 2, 3])

In [77]:
x[0][2][2]

tensor(9)

In [80]:
x[:, :, 1]

tensor([[2, 5, 8]])

# Pytorch tensors and Numpy

In [82]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))